### ISSUE TITLE
Handling groups in cluster scripts

### ISSUE THREAD

**Issue by SilasK** [Snakemake-Profiles/doc#9]
I updated to snakemake v5 and started using groups. Now my cluster_submitter script breaks and doesn't find the information in the cluster config file (`--cluster`). Apparently not even the default values can be used. 

How should we write the definitions for groups in the cluster config file?

**Comment by SilasK** [comment]
Here my full trace back. 

I started using groups with snakemake v5.2.1
my cluster_submitter.py which worked before started creating bugs. 

I have a cluste_config file in yaml format, but tried also with a json formated file? Does the new snakemake version no longer support yaml format but only json? 



```
group job qc (jobs in lexicogr. order):

    rule calculate_insert_size:
...
    rule get_read_stats:
...

Traceback (most recent call last):
  File "/home/kiesers/.config/snakemake/atlas_slurm/slurm_scheduler.py", line 15, in <module>
    job_properties = read_job_properties(jobscript)
  File "/home/kiesers/Programs/anaconda3/envs/atlas/lib/python3.6/site-packages/snakemake/utils.py", line 355, in read_job_properties
    return json.loads(m.group(1))
  File "/home/kiesers/Programs/anaconda3/envs/atlas/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/kiesers/Programs/anaconda3/envs/atlas/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/kiesers/Programs/anaconda3/envs/atlas/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Error submitting jobscript (exit code 1):

```

**Comment by johanneskoester** [comment]
YAML is fine. It looks like read_job_properties has a bug that only occurs when using groups. I will have a look.

**Comment by johanneskoester** [comment]
Ok, fixed in the master branch of Snakemake. I will provide a new release soon.

**Comment by SilasK** [comment]
I think, the problem is not completely solved. The submission works without problem, but I got an error that the 'rule' key is not accessible when submitting a group. 
```
 job_properties['rule']
KeyError: 'rule'

````
Do I have to, make an if clause to check if the key 'rule' is present? 

I normally use the rule name to give the cluster submission a name.
Is there an attribute of group submission that I can use instead?

**Comment by johanneskoester** [comment]
Does the error occur within the submission script? Then yes. You should check for `job_properties["type"]` to be `single` to see if it is an ordinary job. For groups, this will be `group`.
